# Generated by Django 3.1 on 2020-08-12 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200808_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.articles')),
            ],
        ),
    ]
