# Generated by Django 3.1 on 2020-08-12 17:22

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200812_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Article text'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(verbose_name='Publication date'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=120, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.CharField(max_length=120, verbose_name='Comment author'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(max_length=400, verbose_name='Comment text'),
        ),
        migrations.AlterUniqueTogether(
            name='articles',
            unique_together={('title', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='comments',
            unique_together={('author', 'article')},
        ),
    ]
