# Generated by Django 3.1 on 2020-08-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200812_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Title'),
        ),
        migrations.AlterUniqueTogether(
            name='articles',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='comments',
            unique_together=set(),
        ),
    ]
