# Generated by Django 3.1 on 2020-08-13 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20200813_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 12, 54, 13, 292860), verbose_name='Publication date'),
        ),
    ]
