# Generated by Django 3.1 on 2020-08-13 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20200813_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.articles'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.CharField(max_length=255),
        ),
    ]
