# Generated by Django 3.1 on 2020-08-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_auto_20200813_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_text',
            field=models.CharField(max_length=400),
        ),
    ]
