# Generated by Django 3.1 on 2020-08-17 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0027_articles_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='comment',
        ),
    ]
