# Generated by Django 3.1 on 2020-08-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20200813_1043'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
